#!/bin/bash

echo -n "Checking JS modules... "

if yarn check --integrity --verify-tree --silent; then
  echo "OK 👍"
else
  echo "failed! 💥"
  echo "Updating JS modules..."
  yarn install
fi

exec "$@"
